import { axiosClient } from "@/shared/lib/axiosClient";

export interface CalendarEvent {
    _id?: string;
    userId?: string;
    title: string;
    date: Date | string;
    type: 'deadline' | 'reminder' | 'event';
    scholarshipId?: any; // Populated scholarship object or ID
    reminderPreferences?: {
        email: boolean;
        push: boolean;
        reminderDate?: Date | string;
    };
    note?: string;
    isAutoGenerated?: boolean;
    isGlobal?: boolean;
}

export const calendarService = {
    // Get all calendar events
    getEvents: async () => {
        const response = await axiosClient.get<{ success: boolean; data: CalendarEvent[] }>('/calendar');
        return response.data;
    },

    // Create a new event/reminder
    createEvent: async (eventData: Partial<CalendarEvent>) => {
        const response = await axiosClient.post<{ success: boolean; data: CalendarEvent }>('/calendar', eventData);
        return response.data;
    },

    // Delete an event
    deleteEvent: async (id: string) => {
        const response = await axiosClient.delete<{ success: boolean; message: string }>(`/calendar/${id}`);
        return response.data;
    }
};
